#!/usr/bin/env bash
#
# scripts/fake_rtsp_setup.sh
#
# Sets up a local MediaMTX RTSP relay and publishes a synthetic (or
# provided) test video to it on a loop, so that Sentinel's ingestion
# layer can be exercised end-to-end without access to real CCTV
# hardware.
#
# Usage:
#   ./scripts/fake_rtsp_setup.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
BIN_DIR="${SCRIPT_DIR}/bin"
MEDIAMTX_VERSION="v1.9.1"
MEDIAMTX_TARBALL="mediamtx_${MEDIAMTX_VERSION}_linux_amd64.tar.gz"
MEDIAMTX_URL="https://github.com/bluenviron/mediamtx/releases/download/${MEDIAMTX_VERSION}/${MEDIAMTX_TARBALL}"
MEDIAMTX_BIN="${BIN_DIR}/mediamtx"
MEDIAMTX_CONFIG="${REPO_ROOT}/mediamtx.yml"
SAMPLE_VIDEO="${REPO_ROOT}/sample.mp4"
RTSP_PORT=8554
STREAM_PATH="stream/test1"

log() {
  echo "[fake_rtsp_setup] $*"
}

require_cmd() {
  local cmd="$1"
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "[fake_rtsp_setup] ERROR: required command '${cmd}' not found on PATH." >&2
    exit 1
  fi
}

require_cmd curl
require_cmd tar
require_cmd ffmpeg

mkdir -p "${BIN_DIR}"

# ---------------------------------------------------------------------
# 1. Download MediaMTX if not already present.
# ---------------------------------------------------------------------
if [ -x "${MEDIAMTX_BIN}" ]; then
  log "MediaMTX binary already present at ${MEDIAMTX_BIN}. Skipping download."
else
  log "Downloading MediaMTX ${MEDIAMTX_VERSION} for linux/amd64..."
  TMP_TARBALL="$(mktemp -d)/${MEDIAMTX_TARBALL}"
  curl -fL --retry 3 -o "${TMP_TARBALL}" "${MEDIAMTX_URL}"

  log "Extracting MediaMTX into ${BIN_DIR}..."
  tar -xzf "${TMP_TARBALL}" -C "${BIN_DIR}"

  chmod +x "${MEDIAMTX_BIN}"
  rm -f "${TMP_TARBALL}"
  log "MediaMTX installed at ${MEDIAMTX_BIN}."
fi

# ---------------------------------------------------------------------
# 2. Generate a local mediamtx.yml with an RTSP/TCP path for the test
#    stream.
# ---------------------------------------------------------------------
log "Writing MediaMTX configuration to ${MEDIAMTX_CONFIG}..."
cat > "${MEDIAMTX_CONFIG}" <<EOF
###############################################################################
# Auto-generated by scripts/fake_rtsp_setup.sh
# Minimal MediaMTX config exposing a single RTSP/TCP test path for
# Sentinel ingestion smoke testing.
###############################################################################

logLevel: info
logDestinations: [stdout]

# RTSP server settings
rtsp: yes
protocols: [tcp]
rtspAddress: :${RTSP_PORT}
rtspTransports: [tcp]
rtspEncryption: "no"

# Disable unrelated protocols for a minimal footprint.
rtmp: no
hls: no
webrtc: no
srt: no

paths:
  ${STREAM_PATH}:
    source: publisher
EOF

log "MediaMTX configuration written."

# ---------------------------------------------------------------------
# 3. Probe for sample.mp4; synthesize one via ffmpeg testsrc if absent.
# ---------------------------------------------------------------------
if [ -f "${SAMPLE_VIDEO}" ]; then
  log "Found existing sample video at ${SAMPLE_VIDEO}. Reusing it."
else
  log "No sample.mp4 found at repo root. Synthesizing a 30s test pattern video..."
  ffmpeg -y \
    -f lavfi -i "testsrc=size=1280x720:rate=30" \
    -f lavfi -i "sine=frequency=1000:sample_rate=48000" \
    -t 30 \
    -c:v libx264 -pix_fmt yuv420p -preset veryfast \
    -c:a aac -b:a 128k \
    "${SAMPLE_VIDEO}"
  log "Synthetic sample video written to ${SAMPLE_VIDEO}."
fi

# ---------------------------------------------------------------------
# 4. Launch MediaMTX in the background.
# ---------------------------------------------------------------------
log "Starting MediaMTX server on RTSP port ${RTSP_PORT}..."
(
  cd "${REPO_ROOT}"
  nohup "${MEDIAMTX_BIN}" "${MEDIAMTX_CONFIG}" > "${SCRIPT_DIR}/mediamtx.log" 2>&1 &
  echo $! > "${SCRIPT_DIR}/mediamtx.pid"
)
sleep 2
log "MediaMTX started (PID $(cat "${SCRIPT_DIR}/mediamtx.pid")). Logs: ${SCRIPT_DIR}/mediamtx.log"

# ---------------------------------------------------------------------
# 5. Publish the sample video to the RTSP path on a loop, in the
#    background.
# ---------------------------------------------------------------------
log "Starting looped FFmpeg RTSP publisher for rtsp://localhost:${RTSP_PORT}/${STREAM_PATH}..."
(
  cd "${REPO_ROOT}"
  nohup ffmpeg -re -stream_loop -1 -i "${SAMPLE_VIDEO}" \
    -c:v libx264 -preset veryfast -pix_fmt yuv420p \
    -c:a aac -b:a 128k \
    -f rtsp -rtsp_transport tcp \
    "rtsp://localhost:${RTSP_PORT}/${STREAM_PATH}" \
    > "${SCRIPT_DIR}/ffmpeg_publisher.log" 2>&1 &
  echo $! > "${SCRIPT_DIR}/ffmpeg_publisher.pid"
)
sleep 2
log "FFmpeg publisher started (PID $(cat "${SCRIPT_DIR}/ffmpeg_publisher.pid")). Logs: ${SCRIPT_DIR}/ffmpeg_publisher.log"

# ---------------------------------------------------------------------
# 6. Print validation instructions.
# ---------------------------------------------------------------------
cat <<EOF

===============================================================================
Fake RTSP environment is up.

  MediaMTX PID          : $(cat "${SCRIPT_DIR}/mediamtx.pid")
  FFmpeg publisher PID   : $(cat "${SCRIPT_DIR}/ffmpeg_publisher.pid")
  RTSP stream URL        : rtsp://localhost:${RTSP_PORT}/${STREAM_PATH}

Validate the stream with:

  ffplay -rtsp_transport tcp rtsp://localhost:8554/stream/test1

To stop the background processes:

  kill \$(cat "${SCRIPT_DIR}/mediamtx.pid")
  kill \$(cat "${SCRIPT_DIR}/ffmpeg_publisher.pid")

===============================================================================
EOF
